1.6 simple ADT
arrow-kt/Category-Theory-for-Programmers.kt pull request #38
Opened 2019-03-20 14:50 UTC by i-walker

I wasn't sure when to do either
fun ...
or 
val ...

I am open for any changes. 

Shouldn't we provide some solutions to the challenges after everything is translated? 
In my repo, I have a branch for the latter.

2019-03-20 15:05 UTC, i-walker commented
These are my errors, maybe Travis has an idea. 

<img width="1336" alt="Screenshot 2019-03-20 at 16 01 50" src="https://user-images.githubusercontent.com/46971368/54695294-f48af300-4b29-11e9-86e6-072a901a5c39.png">
<img width="966" alt="Screenshot 2019-03-20 at 16 01 39" src="https://user-images.githubusercontent.com/46971368/54695297-f654b680-4b29-11e9-9b16-4dcaabdccd69.png">

2019-03-20 16:51 UTC, raulraja commented
This shouldn't use MaybeK. Did you mean to use Option from arrow.core?

2019-03-20 17:49 UTC, i-walker commented
I tried to replicate this in kotlin. 
<img width="500" alt="Screenshot 2019-03-20 at 18 48 53" src="https://user-images.githubusercontent.com/46971368/54707228-eac0ba00-4b40-11e9-9723-8a17c05bae21.png">

2019-03-20 21:27 UTC, raulraja commented
That in Kotlin and in Arrow is:
```kotlin
sealed class Option<out A>
object None : Option<Nothing>()
data class Some<out A>(a: A): Option<A>()
```

2019-03-22 22:25 UTC, raulraja requested changes
great stuff but we need to get some Kotlin idioms right in the way Kotlin users would spect this. No aliases, sealed classes for sum types and ensure all code snippets that can be type checked are.

2019-03-22 22:25 UTC, raulraja commented on src/main/ank/1.6-simple-algebraic-data-types.md
> +val alpha_inv: (Pair<A, Pair<B, C>>) -> Pair<Pair<A, B>, C>  =
Since we have to use TupleN let's just use Tuple from arrow for all cases and not Pair so there is no chance of confusion to readers

2019-03-22 22:25 UTC, raulraja commented on src/main/ank/1.6-simple-algebraic-data-types.md
> +typealias Either<A, B> = Coproduct2<Left<A>, Right<B>>
Coproduct does not belong here

2019-03-22 22:25 UTC, raulraja commented on src/main/ank/1.6-simple-algebraic-data-types.md
> +typealias Color = Coproduct3<Red, Green, Blue>
This is better expressed with sealed classes and not the coproduct data type which are the equivalent to sum the. Coproduct itself let's you represent that but the Kotlin way to represent this is sealed class adts

2019-03-22 22:25 UTC, raulraja commented on src/main/ank/1.6-simple-algebraic-data-types.md
> +    data class Cons<A>(val head: A, val tail: List<A>) : List<A>()
`Cons<out A>`

2019-03-22 22:25 UTC, raulraja commented on src/main/ank/1.6-simple-algebraic-data-types.md
> +typealias Maybe<A> = Option<A>
No need to alias

2019-03-22 22:25 UTC, raulraja commented on src/main/ank/1.6-simple-algebraic-data-types.md
> +```kotlin
why aren't these checked with ank?

2019-03-23 12:14 UTC, i-walker commented on src/main/ank/1.6-simple-algebraic-data-types.md
> +typealias Maybe<A> = Option<A>
Is this version fine:
```kotlin
@higherkind
sealed class Either<out A, out B> : EitherOf<A, B> {
    //… simplified
    data class Left<out A>(val a: A) : Either<A, Nothing>() 
    data class Right<out B>(val b: B) : Either<Nothing, B>()
}
```

2019-03-23 22:49 UTC, raulraja commented
Yep, though you can leave out the higherkind part and EitherOf out of the
code if you want since those types are not explained

On Sat, Mar 23, 2019, 1:14 PM Imran Settuba <notifications@github.com>
wrote:

> *@i-walker* commented on this pull request.
> ------------------------------
>
> In src/main/ank/1.6-simple-algebraic-data-types.md
> <https://github.com/arrow-kt/Category-Theory-for-Programmers.kt/pull/38#discussion_r268392651>
> :
>
> > +```
>
> +```kotlin:ank:silent
>
> +sealed class List<out A> {
>
> +    object Nil : List<Nothing>()
>
> +    data class Cons<A>(val head: A, val tail: List<A>) : List<A>()
>
> +}
>
> +```
>
> +................
>
> +```Haskell
>
> +maybeTail :: List a -> Maybe (List a)
>
> +maybeTail Nil = Nothing
>
> +maybeTail (Cons _ t) = Just t
>
> +```
>
> +```kotlin:ank:silent
>
> +import arrow.core.Option
>
> +typealias Maybe<A> = Option<A>
>
>
> Is this version fine:
>
> @higherkind
> sealed class Either<out A, out B> : EitherOf<A, B> {
>
>     //… simplified
>
>     data class Left<out A>(val a: A) : Either<A, Nothing>()
>
>     data class Right<out B>(val b: B) : Either<Nothing, B>()
>
> }
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/arrow-kt/Category-Theory-for-Programmers.kt/pull/38#discussion_r268392651>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAb4XIPvorKGuzRKpzOGVgXIW8FDapbfks5vZhqLgaJpZM4b_fln>
> .
>

2019-03-24 09:50 UTC, i-walker commented
I am trying to make this work, but ank can't infer the function: 

```kotlin:ank:silent
import arrow.core.Option.*

fun <A> maybeTail(l:List<A>): Option<List<A>> =
    when(l){
        is List.Nil -> Option.empty()
        is List.Cons -> Option.just(l.tail)
    }
```

```markdown
Exception in thread "main" 

```

import arrow.core.Option.*

fun <A> maybeTail(l:List<A>): Option<List<A>> =
    when(l){
        is List.Nil -> Option.empty()
        is List.Cons -> Option.just(l.tail)
    }
```
error: unresolved reference: empty
        is List.Nil -> Option.empty()
                              ^
error: unresolved reference: just
        is List.Cons -> Option.just(l.tail)
                               ^


> Task :runAnk FAILED

FAILURE: Build failed with an exception.
```

2019-03-24 10:14 UTC, i-walker commented
I am not sure why ank won't compile this..
```markdown
Exception in thread "main" 

```

import arrow.core.*

fun <A, B, C> prodToSum(): (Tuple2<A, Either<B, C>>) -> Either<Tuple2<A, B>, Tuple2<A, C>> =
    {tuple -> tuple.b.fold(
        {b:B -> Left(tuple.a toT b)},
        {c:C -> Right(tuple.a toT c) }
    )}
```
error: unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public inline fun <T, R> Array<out ???>.fold(initial: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, operation: (acc: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, ???) -> Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>): Line_11.Either<Tuple2<A, B>, Tuple2<A, C>> defined in kotlin.collections
public inline fun <R> BooleanArray.fold(initial: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, operation: (acc: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, Boolean) -> Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>): Line_11.Either<Tuple2<A, B>, Tuple2<A, C>> defined in kotlin.collections
public inline fun <R> ByteArray.fold(initial: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, operation: (acc: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, Byte) -> Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>): Line_11.Either<Tuple2<A, B>, Tuple2<A, C>> defined in kotlin.collections
public inline fun <R> CharArray.fold(initial: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, operation: (acc: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, Char) -> Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>): Line_11.Either<Tuple2<A, B>, Tuple2<A, C>> defined in kotlin.collections
public inline fun <R> CharSequence.fold(initial: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, operation: (acc: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, Char) -> Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>): Line_11.Either<Tuple2<A, B>, Tuple2<A, C>> defined in kotlin.text
public inline fun <R> DoubleArray.fold(initial: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, operation: (acc: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, Double) -> Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>): Line_11.Either<Tuple2<A, B>, Tuple2<A, C>> defined in kotlin.collections
public inline fun <R> FloatArray.fold(initial: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, operation: (acc: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, Float) -> Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>): Line_11.Either<Tuple2<A, B>, Tuple2<A, C>> defined in kotlin.collections
public inline fun <R> IntArray.fold(initial: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, operation: (acc: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, Int) -> Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>): Line_11.Either<Tuple2<A, B>, Tuple2<A, C>> defined in kotlin.collections
public inline fun <R> LongArray.fold(initial: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, operation: (acc: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, Long) -> Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>): Line_11.Either<Tuple2<A, B>, Tuple2<A, C>> defined in kotlin.collections
@InlineOnly @SinceKotlin public inline fun <R, T> Result<B>.fold(onSuccess: (value: B) -> Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, onFailure: (exception: Throwable) -> Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>): Line_11.Either<Tuple2<A, B>, Tuple2<A, C>> defined in kotlin
public inline fun <R> ShortArray.fold(initial: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, operation: (acc: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, Short) -> Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>): Line_11.Either<Tuple2<A, B>, Tuple2<A, C>> defined in kotlin.collections
@SinceKotlin public inline fun <T, K, R> Grouping<???, ???>.fold(initialValueSelector: (???, ???) -> ???, operation: (???, ???, ???) -> ???): Map<???, ???> defined in kotlin.collections
@SinceKotlin public inline fun <T, K, R> Grouping<???, ???>.fold(initialValue: ???, operation: (???, ???) -> ???): Map<???, ???> defined in kotlin.collections
public inline fun <T, R> Iterable<???>.fold(initial: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, operation: (acc: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, ???) -> Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>): Line_11.Either<Tuple2<A, B>, Tuple2<A, C>> defined in kotlin.collections
public inline fun <T, R> Sequence<???>.fold(initial: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, operation: (acc: Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>, ???) -> Line_11.Either<Tuple2<A, B>, Tuple2<A, C>>): Line_11.Either<Tuple2<A, B>, Tuple2<A, C>> defined in kotlin.sequences
    {tuple -> tuple.b.fold(
                      ^


> Task :runAnk FAILED

FAILURE: Build failed with an exception.
```

2019-03-24 11:58 UTC, pakoito commented
Extract `b` to a variable typed as Either, then call `fold` on it. Apparently the compiler fails to find it.

2019-03-24 15:05 UTC, raulraja commented
Ank is remembering your previous definitions . Use ank playground blocks
instead which require all imports

On Sun, Mar 24, 2019, 12:58 PM Paco <notifications@github.com> wrote:

> Extract b to a variable typed as Either, then call fold on it. Apparently
> the compiler fails to find it.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/arrow-kt/Category-Theory-for-Programmers.kt/pull/38#issuecomment-475951913>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAb4XDg8vCgDqwxWcNNCgAtGYkfHxfXRks5vZ2h2gaJpZM4b_fln>
> .
>

2019-03-24 22:55 UTC, i-walker commented
Tried it before.
The interesting thing is, that if I execute ank only on the last two functions it works out perfectly. 
What I purpose is that I split this file into two. Maybe Ank can't process long files... 

> Ank is remembering your previous definitions . Use ank playground blocks instead which require all imports
> […](#)
> On Sun, Mar 24, 2019, 12:58 PM Paco ***@***.***> wrote: Extract b to a variable typed as Either, then call fold on it. Apparently the compiler fails to find it. — You are receiving this because you commented. Reply to this email directly, view it on GitHub <[#38 (comment)](https://github.com/arrow-kt/Category-Theory-for-Programmers.kt/pull/38#issuecomment-475951913)>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AAb4XDg8vCgDqwxWcNNCgAtGYkfHxfXRks5vZ2h2gaJpZM4b_fln> .

2019-03-24 23:19 UTC, i-walker commented
What is the difference between [ank-gradle-plugin](https://oss.jfrog.org/artifactory/oss-snapshot-local/io/arrow-kt/ank-gradle-plugin/) and [arrow-ank-gradle](https://oss.jfrog.org/artifactory/oss-snapshot-local/io/arrow-kt/arrow-ank-gradle/)? 
Shouldn't this project use the latest ank gradle Snapshot ? // the latter

2019-03-25 15:41 UTC, raulraja requested changes
we just need to turn all those verifiable snippets into ank blocks and this is good to go. Thanks!

2019-03-25 15:41 UTC, raulraja commented on build.gradle
> +        classpath "io.arrow-kt:ank-gradle-plugin:0.7.0-SNAPSHOT"
this is no longer shipped like this, it's an artifact now that follows the same arrow version 0.9.0

2019-03-25 15:41 UTC, raulraja commented on src/main/ank/1.6-simple-algebraic-data-types-Part1.md
> +```kotlin
this can be checked with ank

2019-03-25 15:41 UTC, raulraja commented on src/main/ank/1.6-simple-algebraic-data-types-Part1.md
> +```kotlin
should be checked with ank

2019-03-25 15:41 UTC, raulraja commented on src/main/ank/1.6-simple-algebraic-data-types-Part1.md
> +```kotlin
should be checked with ank

2019-03-25 15:41 UTC, raulraja commented on src/main/ank/1.6-simple-algebraic-data-types-Part1.md
> +```kotlin
should be checked with ank

2019-03-25 15:41 UTC, raulraja commented on src/main/ank/1.6-simple-algebraic-data-types-Part1.md
> +```kotlin
should be checked with ank and use Kotlin naming conventions

2019-03-25 15:41 UTC, raulraja commented on src/main/ank/1.6-simple-algebraic-data-types-Part1.md
> +fun <A, B> `(,)`(fst:A, snd:B): Tuple2<A, B> = fst toT snd
can be declared as an infix receiver function:
```kotlin
fun <A, B> A.`,`(snd:B): Tuple2<A, B> = this toT snd

1 `,` "a" // (1, "a")
```

2019-03-25 15:41 UTC, raulraja commented on src/main/ank/1.6-simple-algebraic-data-types-Part1.md
> +sealed class Option<out A> : OptionOf<A>{
remove `OptionOf` if you are not gonna place `@higherkind` which is fine for this example

2019-03-25 15:42 UTC, raulraja requested changes
we just need to turn all those verifiable snippets into ank blocks and this is good to go. Thanks!

2019-03-25 17:30 UTC, raulraja commented on build.gradle
> +        classpath "io.arrow-kt:arrow-ank-gradle:0.9.0-SNAPSHOT"
this can be fixed to `0.9.1-SNAPSHOT` or `0.9.0`

2019-03-25 17:32 UTC, raulraja approved these changes

2019-03-25 17:32 UTC, raulraja commented
Excellent, thanks! 👏

2019-03-25 17:33 UTC, i-walker commented
maybe we should then port every arrow module to the 0.9.1 Snapshot. Because they won't be relevant later right?

2019-03-25 17:34 UTC, raulraja commented
yes, but that can be done in a separate PR. Thanks!

2019-03-25 17:35 UTC, merged

2019-03-25 17:36 UTC, raulraja commented
https://github.com/arrow-kt/Category-Theory-for-Programmers.kt/issues/39